### ISSUE TITLE
关于仓库中scss代码的相关问题想请教下

### ISSUE THREAD

**Issue by AsherSun** [elf-templates/video#2]
```scss
@mixin image-background($name) {
  $url: '../img/#{$name}.png';
  width: width($url);
  height: height($url);
  background-image: url($url);
  background-repeat: no-repeat;
  background-size: width($url) auto;
}
```

+ <code>widht($rul)</code> 方法应该不是scss 内置的方法吧？我查了下scss的文档，没有找到。
+ 如果不是scss 内置的方法，那么我也没有在相关的代码上下文中找到该<code>width($rul)</code>方法的实现。想知道 <code>width($rul)</code> 的具体实现和工作机制。谢谢 @booxood @koppthe
